import Providers from '@/providers'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import Header from '../components/header'
import Navigation from '../components/navigation.components'
import './globals.css'


const raleway = Raleway({
  weight: '500',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${raleway.className}`}>
      <body>
        <Providers>
          <main className='grid'>
            <Header />
            <section className='flex'>
              <Navigation />
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  )
}
